// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: user/type.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	MiddleName    *string                `protobuf:"bytes,4,opt,name=middleName,proto3,oneof" json:"middleName,omitempty"`
	Nickname      *string                `protobuf:"bytes,5,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   *string                `protobuf:"bytes,7,opt,name=phoneNumber,proto3,oneof" json:"phoneNumber,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,8,opt,name=createdAt,proto3,oneof" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_type_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetMiddleName() string {
	if x != nil && x.MiddleName != nil {
		return *x.MiddleName
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

var File_user_type_proto protoreflect.FileDescriptor

const file_user_type_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/type.proto\x12\x04user\"\xa6\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12#\n" +
	"\n" +
	"middleName\x18\x04 \x01(\tH\x00R\n" +
	"middleName\x88\x01\x01\x12\x1f\n" +
	"\bnickname\x18\x05 \x01(\tH\x01R\bnickname\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12%\n" +
	"\vphoneNumber\x18\a \x01(\tH\x02R\vphoneNumber\x88\x01\x01\x12!\n" +
	"\tcreatedAt\x18\b \x01(\tH\x03R\tcreatedAt\x88\x01\x01B\r\n" +
	"\v_middleNameB\v\n" +
	"\t_nicknameB\x0e\n" +
	"\f_phoneNumberB\f\n" +
	"\n" +
	"_createdAtB\x15Z\x13proto.user.v1;protob\x06proto3"

var (
	file_user_type_proto_rawDescOnce sync.Once
	file_user_type_proto_rawDescData []byte
)

func file_user_type_proto_rawDescGZIP() []byte {
	file_user_type_proto_rawDescOnce.Do(func() {
		file_user_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_type_proto_rawDesc), len(file_user_type_proto_rawDesc)))
	})
	return file_user_type_proto_rawDescData
}

var file_user_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_type_proto_goTypes = []any{
	(*User)(nil), // 0: user.User
}
var file_user_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_type_proto_init() }
func file_user_type_proto_init() {
	if File_user_type_proto != nil {
		return
	}
	file_user_type_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_type_proto_rawDesc), len(file_user_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_type_proto_goTypes,
		DependencyIndexes: file_user_type_proto_depIdxs,
		MessageInfos:      file_user_type_proto_msgTypes,
	}.Build()
	File_user_type_proto = out.File
	file_user_type_proto_goTypes = nil
	file_user_type_proto_depIdxs = nil
}
